// <auto-generated />
using System;
using FitCycle.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitCycle.Infrastructure.Migrations
{
    [DbContext(typeof(FitCycleDbContext))]
    [Migration("20260228160019_AddWeightColumn")]
    partial class AddWeightColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("FitCycle.Core.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://wger.de/media/exercise-images/192/Bench-press-1.png",
                            MuscleGroupId = 1,
                            Name = "Press banca"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://wger.de/media/exercise-images/41/Incline-bench-press-1.png",
                            MuscleGroupId = 1,
                            Name = "Press inclinado"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://wger.de/media/exercise-images/238/2fc242d3-5bdd-4f97-99bd-678adb8c96fc.png",
                            MuscleGroupId = 1,
                            Name = "Aperturas"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://wger.de/media/exercise-images/83/Bench-dips-1.png",
                            MuscleGroupId = 1,
                            Name = "Fondos"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg",
                            MuscleGroupId = 2,
                            Name = "Dominadas"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://wger.de/media/exercise-images/109/Barbell-rear-delt-row-1.png",
                            MuscleGroupId = 2,
                            Name = "Remo con barra"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://wger.de/media/exercise-images/158/02e8a7c3-dc67-434e-a4bc-77fdecf84b49.webp",
                            MuscleGroupId = 2,
                            Name = "Jalón al pecho"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://wger.de/media/exercise-images/81/a751a438-ae2d-4751-8d61-cef0e9292174.png",
                            MuscleGroupId = 2,
                            Name = "Remo con mancuerna"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://wger.de/media/exercise-images/418/fa2a2207-43cb-4dc0-bc2a-039e32544790.png",
                            MuscleGroupId = 3,
                            Name = "Press militar"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://wger.de/media/exercise-images/148/lateral-dumbbell-raises-large-2.png",
                            MuscleGroupId = 3,
                            Name = "Elevaciones laterales"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://wger.de/media/exercise-images/256/b7def5bc-2352-499b-b9e5-fff741003831.png",
                            MuscleGroupId = 3,
                            Name = "Elevaciones frontales"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://wger.de/media/exercise-images/829/ad724e5c-b1ed-49e8-9279-a17545b0dd0b.png",
                            MuscleGroupId = 3,
                            Name = "Pájaros"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://wger.de/media/exercise-images/74/Bicep-curls-1.png",
                            MuscleGroupId = 4,
                            Name = "Curl con barra"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://wger.de/media/exercise-images/81/Biceps-curl-1.png",
                            MuscleGroupId = 4,
                            Name = "Curl con mancuernas"
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://wger.de/media/exercise-images/86/Bicep-hammer-curl-1.png",
                            MuscleGroupId = 4,
                            Name = "Curl martillo"
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://wger.de/media/exercise-images/1649/441cc0e5-eca2-4828-8b0a-a0e554abb2ff.jpg",
                            MuscleGroupId = 4,
                            Name = "Curl concentrado"
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://wger.de/media/exercise-images/194/34600351-8b0b-4cb0-8daa-583537be15b0.png",
                            MuscleGroupId = 5,
                            Name = "Fondos en paralelas"
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://wger.de/media/exercise-images/1185/c5ca283d-8958-4fd8-9d59-a3f52a3ac66b.jpg",
                            MuscleGroupId = 5,
                            Name = "Extensión con polea"
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://wger.de/media/exercise-images/84/Lying-close-grip-triceps-press-to-chin-1.png",
                            MuscleGroupId = 5,
                            Name = "Press francés"
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://placehold.co/400x300/EEE/31343C.png?font=montserrat&text=Patada%20triceps",
                            MuscleGroupId = 5,
                            Name = "Patada de tríceps"
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://wger.de/media/exercise-images/1805/f166c599-4c03-42a0-9250-47f82a1f096d.jpg",
                            MuscleGroupId = 6,
                            Name = "Sentadilla"
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://wger.de/media/exercise-images/371/d2136f96-3a43-4d4c-9944-1919c4ca1ce1.webp",
                            MuscleGroupId = 6,
                            Name = "Prensa"
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://wger.de/media/exercise-images/851/4d621b17-f6cb-4107-97c0-9f44e9a2dbc6.webp",
                            MuscleGroupId = 6,
                            Name = "Extensión de cuádriceps"
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://wger.de/media/exercise-images/364/b318dde9-f5f2-489f-940a-cd864affb9e3.png",
                            MuscleGroupId = 6,
                            Name = "Curl femoral"
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://wger.de/media/exercise-images/984/5c7ffe68-e7b2-47f3-a22a-f9cc28640432.png",
                            MuscleGroupId = 6,
                            Name = "Zancadas"
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "https://wger.de/media/exercise-images/91/Crunches-1.png",
                            MuscleGroupId = 7,
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "https://wger.de/media/exercise-images/458/b7bd9c28-9f1d-4647-bd17-ab6a3adf5770.png",
                            MuscleGroupId = 7,
                            Name = "Plancha"
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "https://wger.de/media/exercise-images/125/Leg-raises-2.png",
                            MuscleGroupId = 7,
                            Name = "Elevación de piernas"
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "https://wger.de/media/exercise-images/1193/70ca5d80-3847-4a8c-8882-c6e9e485e29e.png",
                            MuscleGroupId = 7,
                            Name = "Russian twist"
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "https://wger.de/media/exercise-images/1614/7f3cfae2-e062-4211-9a6b-5a10851ce7f4.jpg",
                            MuscleGroupId = 8,
                            Name = "Hip thrust"
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "https://wger.de/media/exercise-images/1750/c5ff74e1-b494-4df0-a13f-89c630b88ef9.webp",
                            MuscleGroupId = 8,
                            Name = "Peso muerto rumano"
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "https://wger.de/media/exercise-images/1613/a851fe9d-771f-44da-82f0-799e02ae3fd1.jpg",
                            MuscleGroupId = 8,
                            Name = "Patada de glúteo"
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "https://placehold.co/400x300/EEE/31343C.png?font=montserrat&text=Puente%20gluteos",
                            MuscleGroupId = 8,
                            Name = "Puente de glúteos"
                        });
                });

            modelBuilder.Entity("FitCycle.Core.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pecho"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Espalda"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hombros"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bíceps"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tríceps"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Piernas"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Abdominales"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Glúteos"
                        });
                });

            modelBuilder.Entity("FitCycle.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@fitcycle.local",
                            PasswordHash = "$2a$11$r1zN2HmMy2FnebH4onffcOzWj8IsqmrB0Yxe5k1VgbPzXOh29WGDm",
                            Role = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FitCycle.Core.Models.WorkoutExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutExerciseLogs");
                });

            modelBuilder.Entity("FitCycle.Core.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitCycle.Infrastructure.Entities.DayExerciseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("Day", "ExerciseId");

                    b.ToTable("DayExercises");
                });

            modelBuilder.Entity("FitCycle.Infrastructure.Entities.DayMuscleGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.HasIndex("Day", "MuscleGroupId")
                        .IsUnique();

                    b.ToTable("DayMuscleGroups");
                });

            modelBuilder.Entity("FitCycle.Core.Models.Exercise", b =>
                {
                    b.HasOne("FitCycle.Core.Models.MuscleGroup", "MuscleGroup")
                        .WithMany()
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("FitCycle.Core.Models.WorkoutExerciseLog", b =>
                {
                    b.HasOne("FitCycle.Core.Models.WorkoutSession", "WorkoutSession")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("FitCycle.Infrastructure.Entities.DayExerciseEntity", b =>
                {
                    b.HasOne("FitCycle.Core.Models.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("FitCycle.Infrastructure.Entities.DayMuscleGroupEntity", b =>
                {
                    b.HasOne("FitCycle.Core.Models.MuscleGroup", "MuscleGroup")
                        .WithMany()
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("FitCycle.Core.Models.WorkoutSession", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
